using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OdooCls.Core.Entities
{
    public class RegistroPedido
    {
        public string PHALMA { get; set; } = string.Empty;  // COD.DE ALMACEN (CHARACTER 2)
        public string PHAUTO { get; set; } = string.Empty;  // AUTOR. SOBREGIRO (CHARACTER 10)
        public string PHCLIE { get; set; } = string.Empty;  // Codigo Cliente (CHARACTER 10)
        public string PHCLVT { get; set; } = string.Empty;  // CANAL DE VTA. (CHARACTER 6)
        public string PHCOST { get; set; } = string.Empty;  // CENTRO DE COSTO (CHARACTER 15)
        public string PHCPAG { get; set; } = string.Empty;  // Condicion Pago (CHARACTER 3)
        public string PHDIRC { get; set; } = string.Empty;  // Dirección cliente (CHARACTER 40)
        public string PHDISC { get; set; } = string.Empty;  // Distrito cliente (CHARACTER 30)
        public decimal PHDTIA { get; set; } = 0;                   // Importe Dcto.Ad (NUMERIC 15,2)
        public decimal PHDTOA { get; set; } = 0;                   // %Dcto.Adicional (NUMERIC 5,2)
        public decimal PHEDS2 { get; set; } = 0;                   // T.Valor Descto.2 (NUMERIC 15,2)
        public decimal PHEIGV { get; set; } = 0;                   // T.Valor IGV. (NUMERIC 15,2)
        public decimal PHEPVT { get; set; } = 0;                   // T.Valor Prec.Vta. (NUMERIC 15,2)
        public decimal PHEVVA { get; set; } = 0;                   // T.Valor Vta.Afect (NUMERIC 15,2)
        public decimal PHEVVI { get; set; } = 0;                   // T.Valor Vta.Inaf. (NUMERIC 15,2)
        public int PHFECE { get; set; } = 0;                       // FECHA DE ENTREGA (NUMERIC 8,0)
        public int PHFECP { get; set; } = 0;                       // Fecha de Pedido (NUMERIC 8,0)
        public int PHFEIN { get; set; } = 0;                       // FECHA INGRESO (NUMERIC 8,0)
        public int PHFEMD { get; set; } = 0;                       // FECHA MODIFICA (NUMERIC 8,0)
        public string PHFL01 { get; set; } = string.Empty;  // PEDIDO C/B.O.MANUAL (CHARACTER 1)
        public string PHFL03 { get; set; } = string.Empty;  // PEDIDO DE COTIZACION (CHARACTER 1)
        public string PHFL06 { get; set; } = string.Empty;  // TIPO DE ENTREGA (CHARACTER 1)
        public string PHFL07 { get; set; } = string.Empty;  // EMBALAJE (CHARACTER 1)
        public string PHFL08 { get; set; } = string.Empty;  // CERT.CALIDAD (CHARACTER 1)
        public string PHFL09 { get; set; } = string.Empty;  // 1ER. CAR. ALM.TRANS. (CHARACTER 1)
        public string PHFL10 { get; set; } = string.Empty;  // 2DO. CAR. ALM.TRANS. (CHARACTER 1)
        public string PHFL11 { get; set; } = string.Empty;  // HOJA SEGURIDAD (CHARACTER 1)
        public string PHFL12 { get; set; } = string.Empty;  // CONTINGENCIA (CHARACTER 1)
        public int PHHOIN { get; set; } = 0;                       // HORA INGRESO (NUMERIC 6,0)
        public int PHHOMD { get; set; } = 0;                       // HORA MODIFICA (NUMERIC 6,0)
        public int PHHORP { get; set; } = 0;                       // Hora Pedido (NUMERIC 6,0)
        public int PHMONE { get; set; } = 0;                       // TIPO MONEDA FACTU (NUMERIC 2,0)
        public decimal PHNDS2 { get; set; } = 0;                   // T.Valor Descto.2 (NUMERIC 15,2)
        public string PHNIDE { get; set; } = string.Empty;  // Nro.Doc.Ident. (CHARACTER 15)
        public decimal PHNIGV { get; set; } = 0;                   // T.Valor IGV. (NUMERIC 15,2)
        public string PHNOMC { get; set; } = string.Empty;  // Nombre Cliente (CHARACTER 40)
        public decimal PHNPVT { get; set; } = 0;                   // T.Valor Prec.Vta. (NUMERIC 15,2)
        public int PHNUME { get; set; } = 0;                       // Numero Pedido (NUMERIC 7,0)
        public decimal PHNVVA { get; set; } = 0;                   // T.Valor Vta.Afect (NUMERIC 15,2)
        public decimal PHNVVI { get; set; } = 0;                   // T.Valor Vta.Inaf. (NUMERIC 15,2)
        public string PHORIG { get; set; } = string.Empty;  // Origen Pedido (CHARACTER 1)
        public decimal PHPERE { get; set; } = 0;                   // IMPORTE PERCEPCION ME (NUMERIC 15,2)
        public decimal PHPERN { get; set; } = 0;                   // IMPORTE PERCEPCION MN (NUMERIC 15,2)
        public int PHPVTA { get; set; } = 0;                       // Punto de Venta (NUMERIC 3,0)
        public string PHREF1 { get; set; } = string.Empty;  // ORDEN DE COMPRA (CHARACTER 25)
        public string PHREF2 { get; set; } = string.Empty;  // COD.DE TRANSPORT. (CHARACTER 10)
        public string PHREF3 { get; set; } = string.Empty;  // REF.3 - LIBRE (CHARACTER 10)
        public string PHREF4 { get; set; } = string.Empty;  // REF.4 - LIBRE (CHARACTER 10)
        public string PHREF6 { get; set; } = string.Empty;  // REFERENCIA 6 (CHARACTER 15)
        public string PHREF7 { get; set; } = string.Empty;  // REFERENCIA 7 (CHARACTER 15)
        public decimal PHREF8 { get; set; } = 0;                   // REFERENCIA 8 (NUMERIC 15,6)
        public decimal PHREF9 { get; set; } = 0;                   // REFERENCIA 9 (NUMERIC 15,6)
        public string PHREFA { get; set; } = string.Empty;  // REFERENCIA A (CHARACTER 60)
        public string PHRUBR { get; set; } = string.Empty;  // Rubro de Venta (CHARACTER 1)
        public string PHRUCC { get; set; } = string.Empty;  // R.U.C. cliente (CHARACTER 15)
        public string PHSITD { get; set; } = string.Empty;  // SITUACION DESPACHO (CHARACTER 10)
    [System.ComponentModel.DataAnnotations.RegularExpression("^(01|02|99)$", ErrorMessage = "PHSITU solo permite 01, 02 o 99")]
    public string PHSITU { get; set; } = string.Empty;  // Situación Pedido (CHARACTER 2)
        public decimal PHTCAM { get; set; } = 0;                   // Tipo de Cambio (NUMERIC 15,6)
        public string PHTDOC { get; set; } = string.Empty;  // Fact./Boleta (CHARACTER 2)
        public string PHTIDE { get; set; } = string.Empty;  // Tipo Doc.Ident. (CHARACTER 2)
        public string PHTVTA { get; set; } = string.Empty;  // Tipo de Venta (CHARACTER 2)
        public string PHUSAP { get; set; } = string.Empty;  // Registrado por (CHARACTER 3)
        public string PHUSIN { get; set; } = string.Empty;  // USUARIO INGRESO (CHARACTER 10)
        public string PHUSMD { get; set; } = string.Empty;  // USUARIO MODIFICA (CHARACTER 10)
        public string PHZONA { get; set; } = string.Empty;  // Zona Cliente (CHARACTER 3)
    }
}
