using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OdooCls.Core.Entities
{
    public class RegistroPedidoDetail
    {
        public string PDARTI { get; set; } = string.Empty;  // Codigo Articulo (CHARACTER 20)
        public decimal PDCAN1 { get; set; } = 0;               // CANTIDAD DEVUELTA (NUMERIC 10,3)
        public decimal PDCANT { get; set; } = 0;                   // Cantidad (NUMERIC 10,3)
        public string PDCEQU { get; set; } = string.Empty;  // CODIGO EQUIVALENTE (CHARACTER 25)
        public string PDCLIE { get; set; } = string.Empty;  // Codigo Cliente (CHARACTER 10)
        public string PDCMOA { get; set; } = string.Empty;  // MOTI.ANUL.DOCUM (CHARACTER 6)
        public decimal PDEDS2 { get; set; } = 0;                   // T.Valor Descto.2 (NUMERIC 15,6)
        public decimal PDEIGV { get; set; } = 0;                   // T.Valor IGV. (NUMERIC 15,6)
        public decimal PDEPVT { get; set; } = 0;                   // T.Valor Prec.Vta. (NUMERIC 15,6)
        public decimal PDEVVA { get; set; } = 0;                   // T.Valor Vta.Afect (NUMERIC 15,6)
        public decimal PDEVVI { get; set; } = 0;                   // T.Valor Vta.Inaf. (NUMERIC 15,6)
        public int PDFABO { get; set; } = 0;                       // Nro.Fact./Boleta (NUMERIC 7,0)
        public string PDFBMA { get; set; } = string.Empty;  // Flag BO Manual (CHARACTER 1)
        public int PDFECF { get; set; } = 0;                       // Fecha Facturac. (NUMERIC 8,0)
        public int PDFECG { get; set; } = 0;                       // Fecha de Guia (NUMERIC 8,0)
        public int PDFECP { get; set; } = 0;                       // Fecha de Pedido (NUMERIC 8,0)
        public int PDFECV { get; set; } = 0;                       // Fecha de Vale (NUMERIC 8,0)
        public int PDFEXF { get; set; } = 0;                       // Fec.Anulac.FCBV (DECIMAL 8,0)
        public int PDFVTA { get; set; } = 0;                       // Factor de Venta (NUMERIC 5,0)
        public int PDGUIA { get; set; } = 0;                       // Numero Guia (NUMERIC 7,0)
        public int PDHORF { get; set; } = 0;                       // Hora Facturac. (NUMERIC 6,0)
        public int PDHORG { get; set; } = 0;                       // Hora Guia (NUMERIC 6,0)
        public int PDHOXF { get; set; } = 0;                       // Hora Anulac.FCBV (DECIMAL 6,0)
        public int PDITEM { get; set; } = 0;                       // ITEM CLIENTE (NUMERIC 3,0)
        public string PDLOTE { get; set; } = string.Empty;  // NRO DE LOTE (CHARACTER 10)
        public int PDLPCO { get; set; } = 0;                       // Codigo L.Precio (NUMERIC 7,0)
        public int PDMONE { get; set; } = 0;                       // Moneda del Prec. (NUMERIC 2,0)
        public string PDNART { get; set; } = string.Empty;  // Nombre Articulo (CHARACTER 15)
        public int PDNCOT { get; set; } = 0;                       // NUM.COTIZACION (NUMERIC 7,0)
        public decimal PDNDS2 { get; set; } = 0;                   // T.Valor Descto.2 (NUMERIC 15,6)
        public decimal PDNIGV { get; set; } = 0;                   // T.Valor IGV. (NUMERIC 15,6)
        public decimal PDNPVT { get; set; } = 0;                   // T.Valor Prec.Vta. (NUMERIC 15,6)
        public int PDNUME { get; set; } = 0;                       // Numero Pedido (NUMERIC 7,0)
        public decimal PDNVVA { get; set; } = 0;                   // T.Valor Vta.Afect (NUMERIC 15,6)
        public decimal PDNVVI { get; set; } = 0;                   // T.Valor Vta.Inaf. (NUMERIC 15,6)
        public string PDOBSA { get; set; } = string.Empty;  // OBS.ANULACION (CHARACTER 100)
        public int PDPVTA { get; set; } = 0;                       // Punto de Venta (NUMERIC 3,0)
        public string PDREF0 { get; set; } = string.Empty;  // REFERENCIA 0 (CHARACTER 15)
        public string PDREF1 { get; set; } = string.Empty;  // PORC. DE DESC (CHARACTER 10)
        public string PDREF2 { get; set; } = string.Empty;  // REF2 LIBRE 2 (CHARACTER 10)
        public string PDREF3 { get; set; } = string.Empty;  // REFERENCIA 3 (CHARACTER 20)
        public string PDREF4 { get; set; } = string.Empty;  // REFERENCIA 4 (CHARACTER 20)
        public string PDREF5 { get; set; } = string.Empty;  // REFERENCIA 5 (CHARACTER 15)
        public int PDREF7 { get; set; } = 0;                       // NUMERO DESPACHO (NUMERIC 10,0)
        public string PDREF9 { get; set; } = string.Empty;  // REFERENCIA 9 (CHARACTER 15)
        public string PDREFA { get; set; } = string.Empty;  // REFERENCIA A (CHARACTER 15)
        public string PDRFDE { get; set; } = string.Empty;  // REFERENICA DESPACH (CHARACTER 15)
        public int PDSCOT { get; set; } = 0;                       // SERIE COTIZACION (NUMERIC 3,0)
        public int PDSECC { get; set; } = 0;                       // SECUENCIA COTIZ. (NUMERIC 3,0)
        public int PDSECU { get; set; } = 0;                       // Secuencia (NUMERIC 3,0)
        public string PDSERI { get; set; } = string.Empty;  // NRO DE SERIE (CHARACTER 25)
        public string PDSITD { get; set; } = string.Empty;  // SITUACION DESPACHO (CHARACTER 10)
        public string PDTDOC { get; set; } = string.Empty;  // Fact./Boleta (CHARACTER 2)
        public string PDTVTA { get; set; } = string.Empty;  // Tipo de Venta (CHARACTER 2)
        public decimal PDUNIT { get; set; } = 0;                   // Precio Unitario (NUMERIC 15,4)
        public string PDUNVT { get; set; } = string.Empty;  // UNIDAD DE VENTA (CHARACTER 3)
        public string PDUSAF { get; set; } = string.Empty;  // Facturado por (CHARACTER 10)
        public string PDUSAG { get; set; } = string.Empty;  // Guiado por (CHARACTER 10)
        public string PDUSXF { get; set; } = string.Empty;  // Usr.Anulac.FCBV (CHARACTER 10)
        public int PDVALE { get; set; } = 0;                       // Numero Vale (NUMERIC 6,0) - SE ASIGNA AUTOMÁTICO
        public string PDZONA { get; set; } = string.Empty;  // Zona Cliente (CHARACTER 3)
        public int REQNRO { get; set; } = 0;                       // Num.Requisicion (DECIMAL 8,0)
    }
}
