using OdooCls.Application.Dtos;
using OdooCls.Core.Entities;

namespace OdooCls.Application.Mapper
{
    public static class RegistroMovimientosMapper
    {
        public static RegistroMovimiento MovimientoHeaderToEntity(MovimientoHeaderDto dto)
        {
            return new RegistroMovimiento
            {
                MHALMA = dto.MHALMA,
                MHASTO = dto.MHASTO,
                MHCHOF = dto.MHCHOF,
                MHCMOV = dto.MHCMOV,
                MHCOMP = dto.MHCOMP,
                MHEJER = dto.MHEJER,
                MHFECH = dto.MHFECH,
                MHFEIN = dto.MHFEIN,
                MHFEMD = dto.MHFEMD,
                MHHOIN = dto.MHHOIN,
                MHHOMD = dto.MHHOMD,
                MHHRE1 = dto.MHHRE1,
                MHHRE2 = dto.MHHRE2,
                MHHRE3 = dto.MHHRE3,
                MHPERI = dto.MHPERI,
                MHREF1 = dto.MHREF1,
                MHREF2 = dto.MHREF2,
                MHREF3 = dto.MHREF3,
                MHREF4 = dto.MHREF4,
                MHREF5 = dto.MHREF5,
                MHSITD = dto.MHSITD,
                MHSITU = dto.MHSITU,
                MHTMOV = dto.MHTMOV,
                MHUSEA = dto.MHUSEA,
                MHUSER = dto.MHUSER,
                MHUSIN = dto.MHUSIN,
                MHUSMD = dto.MHUSMD,
                MHVEHI = dto.MHVEHI
            };
        }

        public static RegistroMovimientoDetail MovimientoDetailToEntity(MovimientoDetailDto dto)
        {
            return new RegistroMovimientoDetail
            {
                MDACTI = dto.MDACTI,
                MDALMA = dto.MDALMA,
                MDCANA = dto.MDCANA,
                MDCANR = dto.MDCANR,
                MDCMOV = dto.MDCMOV,
                MDCOAR = dto.MDCOAR,
                MDCOEP = dto.MDCOEP,
                MDCOMO = dto.MDCOMO,
                MDCOMP = dto.MDCOMP,
                MDCORR = dto.MDCORR,
                MDCOSP = dto.MDCOSP,
                MDCOST = dto.MDCOST,
                MDCUEA = dto.MDCUEA,
                MDCUER = dto.MDCUER,
                MDCUNA = dto.MDCUNA,
                MDCUNR = dto.MDCUNR,
                MDDRE0 = dto.MDDRE0,
                MDDRE1 = dto.MDDRE1,
                MDDRE2 = dto.MDDRE2,
                MDDRE4 = dto.MDDRE4,
                MDDRE5 = dto.MDDRE5,
                MDEJER = dto.MDEJER,
                MDFECH = dto.MDFECH,
                MDFVTO = dto.MDFVTO,
                MDLOTE = dto.MDLOTE,
                MDMONO = dto.MDMONO,
                MDPERI = dto.MDPERI,
                MDSITD = dto.MDSITD,
                MDSITU = dto.MDSITU,
                MDTCAM = dto.MDTCAM,
                MDTCMO = dto.MDTCMO,
                MDTMOV = dto.MDTMOV,
                MDTOEC = dto.MDTOEC,
                MDTOTC = dto.MDTOTC,
                MDUMER = dto.MDUMER
            };
        }

        public static RegistroPedido PedidoHeaderToEntity(PedidoHeaderDto dto)
        {
            return new RegistroPedido
            {
                PHALMA = dto.PHALMA,
                PHAUTO = dto.PHAUTO,
                PHCLIE = dto.PHCLIE,
                PHCLVT = dto.PHCLVT,
                PHCOST = dto.PHCOST,
                PHCPAG = dto.PHCPAG,
                PHDIRC = dto.PHDIRC,
                PHDISC = dto.PHDISC,
                PHDTIA = dto.PHDTIA,
                PHDTOA = dto.PHDTOA,
                PHEDS2 = dto.PHEDS2,
                PHEIGV = dto.PHEIGV,
                PHEPVT = dto.PHEPVT,
                PHEVVA = dto.PHEVVA,
                PHEVVI = dto.PHEVVI,
                PHFECE = dto.PHFECE,
                PHFECP = dto.PHFECP,
                PHFEIN = dto.PHFEIN,
                PHFEMD = dto.PHFEMD,
                PHFL01 = dto.PHFL01,
                PHFL03 = dto.PHFL03,
                PHFL06 = dto.PHFL06,
                PHFL07 = dto.PHFL07,
                PHFL08 = dto.PHFL08,
                PHFL09 = dto.PHFL09,
                PHFL10 = dto.PHFL10,
                PHFL11 = dto.PHFL11,
                PHFL12 = dto.PHFL12,
                PHHOIN = dto.PHHOIN,
                PHHOMD = dto.PHHOMD,
                PHHORP = dto.PHHORP,
                PHMONE = dto.PHMONE,
                PHNDS2 = dto.PHNDS2,
                PHNIDE = dto.PHNIDE,
                PHNIGV = dto.PHNIGV,
                PHNOMC = dto.PHNOMC,
                PHNPVT = dto.PHNPVT,
                PHNUME = dto.PHNUME,
                PHNVVA = dto.PHNVVA,
                PHNVVI = dto.PHNVVI,
                PHORIG = dto.PHORIG,
                PHPERE = dto.PHPERE,
                PHPERN = dto.PHPERN,
                PHPVTA = dto.PHPVTA,
                PHREF1 = dto.PHREF1,
                PHREF2 = dto.PHREF2,
                PHREF3 = dto.PHREF3,
                PHREF4 = dto.PHREF4,
                PHREF6 = dto.PHREF6,
                PHREF7 = dto.PHREF7,
                PHREF8 = dto.PHREF8,
                PHREF9 = dto.PHREF9,
                PHREFA = dto.PHREFA,
                PHRUBR = dto.PHRUBR,
                PHRUCC = dto.PHRUCC,
                PHSITD = dto.PHSITD,
                PHSITU = dto.PHSITU,
                PHTCAM = dto.PHTCAM,
                PHTDOC = dto.PHTDOC,
                PHTIDE = dto.PHTIDE,
                PHTVTA = dto.PHTVTA,
                PHUSAP = dto.PHUSAP,
                PHUSIN = dto.PHUSIN,
                PHUSMD = dto.PHUSMD,
                PHZONA = dto.PHZONA
            };
        }

        public static RegistroPedidoDetail PedidoDetailToEntity(PedidoDetailDto dto, int pdvale)
        {
            return new RegistroPedidoDetail
            {
                PDARTI = dto.PDARTI,
                PDCAN1 = dto.PDCAN1,
                PDCANT = dto.PDCANT,
                PDCEQU = dto.PDCEQU,
                PDCLIE = dto.PDCLIE,
                PDCMOA = dto.PDCMOA,
                PDEDS2 = dto.PDEDS2,
                PDEIGV = dto.PDEIGV,
                PDEPVT = dto.PDEPVT,
                PDEVVA = dto.PDEVVA,
                PDEVVI = dto.PDEVVI,
                PDFABO = dto.PDFABO,
                PDFBMA = dto.PDFBMA,
                PDFECF = dto.PDFECF,
                PDFECG = dto.PDFECG,
                PDFECP = dto.PDFECP,
                PDFECV = dto.PDFECV,
                PDFEXF = dto.PDFEXF,
                PDFVTA = dto.PDFVTA,
                PDGUIA = dto.PDGUIA,
                PDHORF = dto.PDHORF,
                PDHORG = dto.PDHORG,
                PDHOXF = dto.PDHOXF,
                PDITEM = dto.PDITEM,
                PDLOTE = dto.PDLOTE,
                PDLPCO = dto.PDLPCO,
                PDMONE = dto.PDMONE,
                PDNART = dto.PDNART,
                PDNCOT = dto.PDNCOT,
                PDNDS2 = dto.PDNDS2,
                PDNIGV = dto.PDNIGV,
                PDNPVT = dto.PDNPVT,
                PDNUME = dto.PDNUME,
                PDNVVA = dto.PDNVVA,
                PDNVVI = dto.PDNVVI,
                PDOBSA = dto.PDOBSA,
                PDPVTA = dto.PDPVTA,
                PDREF0 = dto.PDREF0,
                PDREF1 = dto.PDREF1,
                PDREF2 = dto.PDREF2,
                PDREF3 = dto.PDREF3,
                PDREF4 = dto.PDREF4,
                PDREF5 = dto.PDREF5,
                PDREF7 = dto.PDREF7,
                PDREF9 = dto.PDREF9,
                PDREFA = dto.PDREFA,
                PDRFDE = dto.PDRFDE,
                PDSCOT = dto.PDSCOT,
                PDSECC = dto.PDSECC,
                PDSECU = dto.PDSECU,
                PDSERI = dto.PDSERI,
                PDSITD = dto.PDSITD,
                PDTDOC = dto.PDTDOC,
                PDTVTA = dto.PDTVTA,
                PDUNIT = dto.PDUNIT,
                PDUNVT = dto.PDUNVT,
                PDUSAF = dto.PDUSAF,
                PDUSAG = dto.PDUSAG,
                PDUSXF = dto.PDUSXF,
                PDVALE = pdvale, // SE ASIGNA AUTOMÁTICAMENTE
                PDZONA = dto.PDZONA,
                REQNRO = dto.REQNRO
            };
        }

        // TODO: Agregar métodos para NotaCredito cuando se tenga la info
    }
}
